# Usa una imagen base de Node.js (versión 18 en Alpine para ser ligera)
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias al contenedor
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto del código fuente al contenedor
COPY . .

# Compila el código TypeScript (asegúrate de tener un script "build" en package.json)
RUN npm run tsc

# Expone el puerto en el que tu aplicación escucha (por ejemplo, 3000)
EXPOSE 3000

# Define el comando para iniciar la aplicación
CMD ["npm", "start"]